### ISSUE TITLE
Echo Gazelle spawn immediate explodes due to spawn collision with static objects 

### ISSUE THREAD

**Issue by Smiggus** [7Cav/Cavhold#10]
On unit list in ME, check Show Hidden Units. Gazelles are spawning in refueler and hanger static.

![image](https://user-images.githubusercontent.com/100982060/191181390-5a622e79-d099-4943-b5cc-5da14c2c746f.png)

**Comment by DrTeemo** [comment]
![image](https://user-images.githubusercontent.com/82063598/192674895-36a9d640-0ab6-4b06-acf4-4dcc0f710d0b.png)

**Comment by DrTeemo** [comment]
Added more space.
![image](https://user-images.githubusercontent.com/82063598/192676658-0623faa7-78d7-49a8-9b2a-321325cd9db7.png)
